### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by superrune** [MichaelKirsch/KintaroSnes#4]
Hi,

I am trying to install this on my RetroPie, but I'm not sure how to process. I've copied all the files into a folder on my Raspberry Pi, but when I run 

**sudo dpkg -i kintarosnes.deb**

I get a couple dependency problems telling me that python3-dialog and python3-rpi.gpio is missing. Am I doing this the wrong way?

**Comment by MichaelKirsch** [comment]
You Need to do the other command i specified too

Gesendet von Mail für Windows 10

Von: superrune
Gesendet: Dienstag, 17. März 2020 22:53
An: MichaelKirsch/KintaroSnes
Cc: Subscribed
Betreff: [MichaelKirsch/KintaroSnes] How to install? (#4)

Hi,
I am trying to install this on my RetroPie, but I'm not sure how to process. I've copied all the files into a folder on my Raspberry Pi, but when I run
sudo dpkg -i kintarosnes.deb
I get a couple dependency problems telling me that python3-dialog and python3-rpi.gpio is missing. Am I doing this the wrong way?

**Comment by MichaelKirsch** [comment]
Both commands are needed

sudo dpkg -i kintarosnes.deb
sudo apt-get install -f


Gesendet von Mail für Windows 10

Von: superrune
Gesendet: Dienstag, 17. März 2020 22:53
An: MichaelKirsch/KintaroSnes
Cc: Subscribed
Betreff: [MichaelKirsch/KintaroSnes] How to install? (#4)

Hi,
I am trying to install this on my RetroPie, but I'm not sure how to process. I've copied all the files into a folder on my Raspberry Pi, but when I run
sudo dpkg -i kintarosnes.deb
I get a couple dependency problems telling me that python3-dialog and python3-rpi.gpio is missing. Am I doing this the wrong way?

**Comment by superrune** [comment]
Thanks for the prompt reply. That worked wonders!

**Comment by MichaelKirsch** [comment]
Glad i could help 😊

Gesendet von Mail für Windows 10

Von: superrune
Gesendet: Dienstag, 17. März 2020 22:59
An: MichaelKirsch/KintaroSnes
Cc: Michael Kirsch; Comment
Betreff: Re: [MichaelKirsch/KintaroSnes] How to install? (#4)

Thanks for the prompt reply. That worked wonders!

**Comment by MichaelKirsch** [comment]
Updated Description
