### ISSUE TITLE
Off button does not work properly

### ISSUE THREAD

**Issue by superrune** [MichaelKirsch/KintaroSnes#5]
Hi,

This is an odd issue. I can turn the Kintaro case on with the power button, the reset button works fine, but pulling the power button off again does not do anything. I can turn the power off, then press reset, and the Kintaro case turns off, but that's not how it is supposed to work, I assume?

Running **sudo systemctl status kintaro** gives me this message with a runtime warning:
```
● kintaro.service - Kintaro PCB-Script
   Loaded: loaded (/etc/systemd/system/kintaro.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-03-18 06:53:54 GMT; 11min ago
 Main PID: 335 (pcb.py)
   CGroup: /system.slice/kintaro.service
           └─335 /usr/bin/python3 -u /opt/kintaro/pcb.py

Mar 18 06:53:54 retropie systemd[1]: Started Kintaro PCB-Script.
Mar 18 06:53:55 retropie kintaro[335]: /opt/kintaro/pcb.py:32: RuntimeWarning: A physical pull up resistor is fitted on this channel!
Mar 18 06:53:55 retropie kintaro[335]:   GPIO.setup(pcb_components["RESET"], GPIO.IN, pull_up_down=GPIO.PUD_UP) #set pin as input and switch on internal pull up resis
```
Can this runtime warning be related to this issue?

**Comment by superrune** [comment]
It seems to be working again after I ran that command. It did not work at all yesterday, but now it seems like its good again. Weird!

**Comment by MichaelKirsch** [comment]
The powerdown is built in hardware and attaches to a interrupt or the raspberrypi. i can not modify it as the "startup" is raspberry controlled. but i have to account for people plugging it in with the powerbutton in the off position. then the device will start and instantly shutdown. so the shutdown is only active when started in the on position. if started in the off position it will need to be switched two times to get active
